// week03/react-full-stack-example/src/TodoList.js
import React from 'react';

export default({ todos, deleteTodo }) => (
  <ul className="list-group mt-2">
    {todos.map(todo =>
      <li className="list-group-item">
        {todo.content}
        <button
          type="button"
          className="btn btn-link btn-sm float-right"
          onClick={() => deleteTodo(todo.id)}
          style={{ lineHeight: 1 }}
        >
          Delete
        </button>
      </li>
    )}
  </ul>
)

// week03/angular-full-stack-example/src/app/todo-list/todo-list.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { TodoService } from "../todo.service";
import { Todo } from "../todo";

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css']
})
export class TodoListComponent {
  @Input() todos: Todo[];

  @Output() todosUpdate = new EventEmitter<Todo[]>();

  constructor(private todoService: TodoService) { }

  deleteTodo(id: string): void {
    this.todoService.deleteTodo(id)
      .subscribe(todos => this.todosUpdate.emit(todos))
  }
}

<ul class="list-group mt-2">
  <li *ngFor="let todo of todos" class="list-group-item">
    {{todo.content}}
    <button type="button" class="btn btn-link btn-sm float-right" style="line-height: 1;"
            (click)="deleteTodo(todo.id)">
      Delete
    </button>
  </li>
</ul>
