// week03/react-full-stack-example/src/Todo.js
import React, { Component } from 'react';

class Todo extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todo: ''
    }
  }

  handleTodoValueUpdate(e) {
    this.setState({ todo: e.target.value })
  }

  handleTodoSubmit() {
    this.props.addTodo(this.state.todo);
    this.setState({ todo: '' });
  }

  render() {
    return (
      <div className="input-group">
        <input
          type="text"
          className="form-control"
          name="todo"
          value={this.state.todo}
          placeholder="What needs to be done?"
          onChange={e => this.handleTodoValueUpdate(e)} // Update input value on key change
          onKeyPress={e => e.key === 'Enter' && this.handleTodoSubmit()} // If enter key pressed, add new todo.
        />
        <div className="input-group-append">
          <button
            type="submit"
            className="btn btn-primary"
            onClick={() => this.handleTodoSubmit()}
          >
            Add
          </button>
        </div>
      </div>
    );
  }
}

export default Todo;

// week02/angular-example/src/app/todo/todo.component.ts
import { Component, OnInit } from '@angular/core';
import { TodoService } from "../todo.service";

@Component({
  selector: 'app-todo',
  templateUrl: './todo.component.html',
  styleUrls: ['./todo.component.css']
})
export class TodoComponent implements OnInit {
  todo: string = '';

  constructor(private todoService: TodoService) { }

  ngOnInit() {
  }

  addTodo(): void {
    if (this.todo) {
      this.todoService.add(this.todo);
      this.todo = '';
    }
  }
}

<div class="input-group">
  <input [(ngModel)]="todo" type="text" class="form-control" name="todo"
         placeholder="What needs to be done?" (keyup.enter)="addTodo()">
  <div class="input-group-append">
    <button class="btn btn-primary" (click)="addTodo()">Add</button>
  </div>
</div>
