// week02/angular-example/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'Todo List';
}

<div class="container">
  <div class="card m-5">
    <h3 class="card-header">{{title}}</h3>
    <div class="card-body">
      <app-todo></app-todo>
      <app-todo-list></app-todo-list>
    </div>
  </div>
</div>

// week02/react-example/src/App.js
import React, { Component } from 'react';
import Todo from './Todo';
import TodoList from './TodoList';

class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todos: []
    }
  }

  addTodo(todo) {
    if (todo) {
      this.setState({
        todos: [...this.state.todos, todo]
      })
    }
  }

  render() {
    return (
      <div className="container">
        <div className="card m-5">
          <h3 className="card-header">Todo List</h3>
          <div className="card-body">
              <Todo addTodo={this.addTodo.bind(this)}/>
              <TodoList todos={this.state.todos}/>
          </div>
        </div>
      </div>
    );
  }
}

export default App;
