// week04/react-router-example/src/TodoEditor.js
import React, { Component } from 'react';
import { Redirect, Link } from 'react-router-dom';
import axios from 'axios';

class TodoEditor extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todo: null,
      fetched: false
    }
  }

  componentDidMount() {
    const locationState = this.props.location.state;
    if (locationState && locationState.todo) {
      // If the todo item is sent by other component, we don't need to fetch from the server
      this.setState({
        todo: locationState.todo,
        fetched: true
      })
    } else {
      axios.get(`/api/todos/${this.props.match.params.id}`)
        .then(response => {
          const todo = response.data;
          this.setState({ todo });
        })
        .catch(error => console.log(error))
        .then(() => this.setState({ fetched: true }))
    }
  }

  handleTodoUpdate(prop, newValue) {
    this.setState({
      todo: { ...this.state.todo, [prop]: newValue }
    });
  }

  handleTodoSubmit() {
    axios.put(`/api/todos/${this.state.todo.id}`, { todo: this.state.todo })
      .then(response => {
        // Navigate to '/' with updated todo list
        this.props.history.push('/', { todos: response.data })
      })
  }

  render() {
    return (
      <div className="card-body">
        {/* Fetching item */}
        {!this.state.fetched && <p>Fetching todo item...</p>}
        {/* If item cannot be found, redirect to '/' */}
        {this.state.fetched && !this.state.todo && <Redirect to='/todo-list'/>}
        {/* If todo is found, render the editor part */}
        {this.state.fetched && this.state.todo &&
        <form>
          <div className="form-group">
            <input
              type="text"
              className="form-control"
              name="todo"
              value={this.state.todo.content}
              placeholder="What needs to be done?"
              onChange={e => this.handleTodoUpdate('content', e.target.value)}
            />
          </div>
          <div className="form-group form-check">
            <input
              type="checkbox"
              className="form-check-input"
              id="isTodoCompleted"
              defaultChecked={this.state.todo.done}
              onChange={e => this.handleTodoUpdate('done', e.target.checked)}
            />
            <label className="form-check-label" htmlFor="isTodoCompleted">Completed</label>
          </div>
          <div className="form-group clearfix">
            <button
              type="button"
              className="btn btn-primary float-right mr-2"
              onClick={() => this.handleTodoSubmit()}
            >
              Submit
            </button>
            <Link
              className="btn btn-danger float-right mr-2"
              to="/todo-list"
            >
              Cancel
            </Link>
          </div>
        </form>
        }
      </div>
    )
  }
}

export default TodoEditor

// week04/angular-router-example/src/app/todo-editor/todo-editor.component.ts
import { Component, OnInit } from '@angular/core';
import { Router, ActivatedRoute } from "@angular/router";
import { Todo } from "../todo";
import { TodoService } from "../todo.service";

@Component({
  selector: 'app-todo-editor',
  templateUrl: './todo-editor.component.html',
  styleUrls: ['./todo-editor.component.css']
})
export class TodoEditorComponent implements OnInit {
  todo: Todo;
  fetched = false;

  constructor(
    private router: Router,
    private route: ActivatedRoute,
    private todoService: TodoService
  ) { }

  ngOnInit() {
    const id = this.route.snapshot.paramMap.get('id');
    this.todo = this.todoService.findTodo(id);
    if (!this.todo) {
      this.todoService.getTodo(id)
        .subscribe(todo => {
          if (todo) {
            this.todo = todo;
          } else {
            this.router.navigate(['/todo-list'])
          }
          this.fetched = true;
        });
    } else {
      this.fetched = true;
    }
  }

  updateTodo() {
    this.todoService.updateTodo(this.todo)
      .subscribe(todos => {
        this.todoService.todos = todos;
        this.router.navigate(['/todo-list'])
      });
  }
}

<h3 class="card-header">Edit todo</h3>
<div class="card-body">
  <p *ngIf="!fetched">Fetching todo item...</p>
  <form *ngIf="fetched && todo">
    <div class="form-group">
      <input [(ngModel)]="todo.content" type="text" class="form-control" name="todo">
    </div>
    <div class="form-group form-check">
      <input [(ngModel)]="todo.done" type="checkbox" class="form-check-input"
             name="completed" id="isTodoCompleted">
      <label class="form-check-label" for="isTodoCompleted">Completed</label>
    </div>
    <div class="form-group clearfix">
      <button type="button" class="btn btn-primary float-right mr-2"
              (click)="updateTodo()">Submit</button>
      <a routerLink="/todo-list" class="btn btn-danger float-right mr-2">Cancel</a>
    </div>
  </form>
</div>
