// week04/react-router-example/src/TodoList.js
import React, { Component } from 'react';
import { Link } from 'react-router-dom';
import axios from 'axios';
import Todo from './Todo';

class TodoList extends Component {
  constructor(props) {
    super(props);
    this.state = {
      todos: []
    };
  }

  componentDidMount() {
    const locationState = this.props.location.state;
    if (locationState && locationState.todos) {
      // If the todo list is sent by other component, we don't need to fetch from the server
      this.setState({ todos: locationState.todos })
    } else {
      axios.get('/api/todos')
        .then(response => {
          const todos = response.data;
          this.setState({ todos });
        })
    }
  }

  addTodo(todo) {
    if (todo.trim() !== '') {
      axios.post('api/todos', { todo })
        .then(response => {
          const todos = response.data;
          this.setState({ todos });
        })
    }
  }

  deleteTodo(id) {
    axios.delete(`/api/todos/${id}`)
      .then(response => {
        const todos = response.data;
        this.setState({ todos });
      })
  }

  render() {
    return (
        <div className="card-body">
          <Todo addTodo={this.addTodo.bind(this)}/>
          <ul className="list-group mt-2">
            {this.state.todos.map(todo =>
              <li className="list-group-item">
                <span style={{ textDecoration: todo.done ? 'line-through' : 'none' }}>
                  {todo.content}
                </span>
                <button
                  type="button"
                  className="btn btn-link btn-sm float-right"
                  onClick={() => this.deleteTodo(todo.id)}
                  style={{ lineHeight: 1 }}
                >
                  Delete
                </button>
                <Link
                  className="btn btn-link btn-sm float-right"
                  style={{ lineHeight: 1 }}
                  to={{
                    pathname: `/todo-editor/${todo.id}`,
                    state: { todo }
                  }}
                >
                  Edit
                </Link>
              </li>
            )}
          </ul>
        </div>
    );
  }
}

export default TodoList;

// week04/angular-router-example/src/app/todo-list/todo-list.component.ts
import { Component, OnInit } from '@angular/core';
import isEmpty from 'lodash/isEmpty';
import { TodoService } from "../todo.service";
import { Todo } from "../todo";

@Component({
  selector: 'app-todo-list',
  templateUrl: './todo-list.component.html',
  styleUrls: ['./todo-list.component.css']
})
export class TodoListComponent implements OnInit {
  todos: Todo[];

  constructor(private todoService: TodoService) { }

  ngOnInit() {
    if (!isEmpty(this.todoService.todos)) {
      this.todos = this.todoService.todos;
    } else {
      this.getTodos()
    }
  }

  getTodos(): void {
    this.todoService.getTodos()
      .subscribe(todos => {
        this.todoService.todos = todos;
        this.todos = todos;
      })
  }

  deleteTodo(id: string): void {
    this.todoService.deleteTodo(id)
      .subscribe(todos => {
        this.todoService.todos = todos;
        this.todos = todos;
      })
  }

  onTodosUpdated(todos: Todo[]): void {
    this.todoService.todos = todos;
    this.todos = todos;
  }
}

<h3 class="card-header">Todo List</h3>
<div class="card-body">
  <app-todo (todosUpdate)="onTodosUpdated($event)"></app-todo>
  <ul class="list-group mt-2">
    <li *ngFor="let todo of todos" class="list-group-item">
      <span [ngStyle]="{'text-decoration': todo.done ? 'line-through' : 'none'}">
        {{todo.content}}
      </span>
      <button type="button" class="btn btn-link btn-sm float-right" style="line-height: 1;"
              (click)="deleteTodo(todo.id)">
        Delete
      </button>
      <a routerLink="/todo-editor/{{todo.id}}" class="btn btn-link btn-sm float-right"
         style="line-height: 1;">
        Edit
      </a>
    </li>
  </ul>
</div>
